name: Run on PR
on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main
    workflow_dispatch:
        inputs:
            project:
                description: 'The project that has to be executed'
                type:
                    choice
                required: true
                default: 'chromium-headless'
                options:
                  - chromium-headless
                  - naukri-tests
                  - dhc-tests-no-auth
                  - blaze-tests
env:
    PROJECT: ${{github.event.inputs.project || 'experimental'}}

jobs:
    build-the-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses:  actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Install Chrome
              run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
            # - name: Install Playwright Browsers
            #   run: npx playwright install chromium --with-deps
            - name: Run project
              run: |
               xvfb-run -a npx playwright test --project $PROJECT --reporter=github,html
            - name: upload reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: test-output
                path: |
                    playwright-report/
                    test-results/
