name: Run on PR
on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main
jobs:
    build-the-code:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/playwright:v1.53.1-noble
        steps:
            - name: Checkout the code
              uses:  actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Run tets
              run: npm run test:ui
